name: lednik

services:
  serving:
    build:
      context: .
      dockerfile: docker/serving.Dockerfile
    container_name: lednik_serving
    environment:
      - MODEL_ID=${MODEL_ID}
      - TOKENIZER_ID=${TOKENIZER_ID}
      - CLEARML_API_ACCESS_KEY=${CLEARML_API_ACCESS_KEY}
      - CLEARML_API_SECRET_KEY=${CLEARML_API_SECRET_KEY}
      - CLEARML_API_HOST=${CLEARML_API_HOST}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - PORT=8080
    ports:
      - '127.0.0.1:8080:8080'
    restart: unless-stopped
