from __future__ import annotations

from collections.abc import Callable
from collections.abc import Iterator
from collections.abc import Mapping
from typing import Any
from typing import Self
from typing import TypeVar
from typing import overload

from torch import Tensor
from torch import device
from torch import dtype
from torch._prims_common import DeviceLikeType
from torch.nn.parameter import Parameter
from torch.utils.hooks import RemovableHandle

_grad_t = Tensor | tuple[Tensor, ...]
T = TypeVar("T", bound="Module")

class _IncompatibleKeys(tuple[tuple[list[str], list[str]]]):
    missing_keys: list[str]
    unexpected_keys: list[str]

def register_module_forward_pre_hook(hook: Callable[..., None]) -> RemovableHandle: ...
def register_module_forward_hook(
    hook: Callable[..., None],
    *,
    with_kwargs: bool = False,
    always_call: bool = False,
) -> RemovableHandle: ...
def register_module_full_backward_pre_hook(
    hook: Callable[[Module, _grad_t], None | _grad_t],
) -> RemovableHandle: ...
def register_module_backward_hook(
    hook: Callable[[Module, _grad_t, _grad_t], None | _grad_t],
) -> RemovableHandle: ...
def register_module_full_backward_hook(
    hook: Callable[[Module, _grad_t, _grad_t], None | _grad_t],
) -> RemovableHandle: ...
def register_module_buffer_registration_hook(
    hook: Callable[..., None],
) -> RemovableHandle: ...
def register_module_module_registration_hook(
    hook: Callable[..., None],
) -> RemovableHandle: ...
def register_module_parameter_registration_hook(
    hook: Callable[..., None],
) -> RemovableHandle: ...

class Module:
    dump_patches: bool
    _version: int
    training: bool

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def forward(self, *args: Any, **kwargs: Any) -> Any: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __setattr__(self, name: str, value: Any) -> None: ...
    def __getattr__(self, name: str) -> Tensor | Module: ...
    def __delattr__(self, name: str) -> None: ...
    def register_buffer(
        self,
        name: str,
        tensor: Tensor | None,
        persistent: bool = True,
    ) -> None: ...
    def register_parameter(self, name: str, param: Parameter | None) -> None: ...
    def add_module(self, name: str, module: Module | None) -> None: ...
    def register_module(self, name: str, module: Module | None) -> None: ...
    def get_submodule(self, target: str) -> Module: ...
    def set_submodule(
        self, target: str, module: Module, strict: bool = False
    ) -> None: ...
    def get_parameter(self, target: str) -> Parameter: ...
    def get_buffer(self, target: str) -> Tensor: ...
    def children(self) -> Iterator[Module]: ...
    def named_children(self) -> Iterator[tuple[str, Module]]: ...
    def modules(self) -> Iterator[Module]: ...
    def named_modules(
        self,
        memo: set[Module] | None = None,
        prefix: str = "",
        remove_duplicate: bool = True,
    ) -> Iterator[tuple[str, Module]]: ...
    def parameters(self, recurse: bool = True) -> Iterator[Parameter]: ...
    def named_parameters(
        self,
        prefix: str = "",
        recurse: bool = True,
        remove_duplicate: bool = True,
    ) -> Iterator[tuple[str, Parameter]]: ...
    def buffers(self, recurse: bool = True) -> Iterator[Tensor]: ...
    def named_buffers(
        self,
        prefix: str = "",
        recurse: bool = True,
        remove_duplicate: bool = True,
    ) -> Iterator[tuple[str, Tensor]]: ...
    def apply(self, fn: Callable[[Module], None]) -> Self: ...
    def cuda(self, device: int | device | None = None) -> Self: ...
    def cpu(self) -> Self: ...
    def xpu(self, device: int | device | None = None) -> Self: ...
    def ipu(self, device: int | device | None = None) -> Self: ...
    def mtia(self, device: int | device | None = None) -> Self: ...
    def float(self) -> Self: ...
    def double(self) -> Self: ...
    def half(self) -> Self: ...
    def bfloat16(self) -> Self: ...
    def to_empty(
        self, *, device: DeviceLikeType | None, recurse: bool = True
    ) -> Self: ...
    @overload
    def to(
        self,
        device: DeviceLikeType | None = ...,
        dtype: dtype | None = ...,
        non_blocking: bool = ...,
    ) -> Self: ...
    @overload
    def to(self, dtype: dtype, non_blocking: bool = ...) -> Self: ...
    @overload
    def to(self, tensor: Tensor, non_blocking: bool = ...) -> Self: ...
    def to(self, *args: Any, **kwargs: Any) -> Self: ...
    @overload
    def state_dict(
        self,
        *,
        destination: dict[str, Any],
        prefix: str = ...,
        keep_vars: bool = ...,
    ) -> dict[str, Any]: ...
    @overload
    def state_dict(
        self,
        *,
        prefix: str = ...,
        keep_vars: bool = ...,
    ) -> dict[str, Any]: ...
    def state_dict(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
    def load_state_dict(
        self,
        state_dict: Mapping[str, Any],
        strict: bool = True,
        assign: bool = False,
    ) -> _IncompatibleKeys: ...
    def train(self, mode: bool = True) -> Self: ...
    def eval(self) -> Self: ...
    def requires_grad_(self, requires_grad: bool = True) -> Self: ...
    def zero_grad(self, set_to_none: bool = True) -> None: ...
    def share_memory(self) -> Self: ...
    def _get_name(self) -> str: ...
    def extra_repr(self) -> str: ...
    def __repr__(self) -> str: ...
    def __dir__(self) -> list[str]: ...
    def compile(self, *args: Any, **kwargs: Any) -> None: ...
