data:
  train_datasets:
    Kinopoisk-Reviews: 4154370acaa644df8ed9e076c75778ae
  val_datasets:
    Kinopoisk-Reviews: 4154370acaa644df8ed9e076c75778ae
  batch_size: 2
  num_workers: 5
  train_tokens_column: USER-bge-m3
  val_tokens_column: USER-bge-m3
  val_label_column: label
  val_num_labels: 3
  max_length: 1024

trainer:
  accelerator: "gpu"
  max_epochs: 1
  strategy:
    type: "ddp"
    find_unused_parameters: true
  val_check_interval: 0.01
  devices: 4
  precision: bf16-true
  log_every_n_steps: 25

early_stopping:
  monitor: "val_loss"
  patience: 3
  mode: "min"
  min_delta: 0.01

checkpoint:
  save_top_k: 3
  mode: "min"
  monitor: "val_loss"
  filename: "{epoch:02d}-{val_loss:.4f}"

teacher_model_id: af954495ff03440abc58790c4e41ff22
student_model_id: 957e87cdf34348d4b93314cd70c57e3c
tokenizer_id: 34beac693bfa4977b23cafea8b3d6379
