grad_clip_val: 2.0
warmup_iters: 2500
warmup_lr: 5e-5
base_lr: 9e-5
weight_decay: 0.001
teacher_dim_reduction_type: autoencoder
student_dim: 300
teacher_dim: 1024
embedding_dropout: 0.2
teacher_pooling_method: cls
student_freeze_iters: 1200
reconstruction_loss_boost_while_frozen: 1.0
reconstruction_loss_weight: 0.3
semantic_loss_weight: 0.7
reduction_dropout: 0.2
