grad_clip_val: 2.0
warmup_iters_ratio: 0.1
warmup_lr: 4e-4
base_lr: 7e-4
final_lr: 1e-4
weight_decay: 0.001
embedding_dropout: 0.15
teacher_pooling_method: cls
distillation_method:
  type: direct
  student_dim: 300
  teacher_dim: 1024
  dim_alignment_type: teacher2student
  teacher_dim_reduction_type: autoencoder
  student_freeze_iters: 500
  reduction_dropout: 0.15
  reconstruction_loss_weight: 0.3
  semantic_loss_weight: 7.0
  reconstruction_loss_boost_while_frozen: 1.0
