data:
  train_datasets:
    Cultura-Ru(train): f3f9ac08e9054d39928853d797a4ab8d
    Lenta-RU(train): c0db0a47494649e8a56c35ab237bd414
  val_datasets:
    Telegram-Financial-Sentiment(val): 15a6b40eb988463a9654e5109f784619
  batch_size: 256
  num_workers: 5
  train_tokens_column: USER-bge-m3
  val_tokens_column: USER-bge-m3
  val_label_column: label
  val_num_labels: 3
  max_length: 1024

trainer:
  accelerator: "gpu"
  max_epochs: 1
  strategy:
    type: "fsdp1"
    param_dtype: bfloat16
    reduce_dtype: float32
    buffer_dtype: float32
  val_check_interval: 0.1
  devices: 2
  precision: 32-true
  log_every_n_steps: 25
  limit_train_batches: 4200

early_stopping:
  monitor: "val_loss"
  patience: 3
  mode: "min"
  min_delta: 0.01

checkpoint:
  save_top_k: 3
  mode: "min"
  monitor: "val_loss"
  filename: "{epoch:02d}-{val_loss:.4f}"

teacher_model_id: af954495ff03440abc58790c4e41ff22
student_model_id: e37f57e81dd54065a96169bd7b1d286d
tokenizer_id: 34beac693bfa4977b23cafea8b3d6379
model_cfg:
  model_type: lednik
  embeddings_dropout: 0.1
  attention_dropout: 0.05
  out_attn_dropout: 0.15
  mlp_dropout: 0.15
