grad_clip_val: 2.0
lr:
  use_scheduler: true
  warmup_iters_ratio: 0.1
  warmup_value: 4e-4
  base_value: 7e-4
  final_value: 1e-4
weight_decay:
  base_value: 0.001
label2id:
  negative: 0
  neutral: 1
  positive: 2
class_weights: [ 0.55, 0.244, 0.206 ]
embedding_dropout: 0.15
classifier_dropout: 0.1
