data:
  datasets:
    Telegram-Financial-Sentiment: f2c2c19d7c1d4366bf1c24e8ab518ce6
  batch_size: 32
  num_workers: 5
  tokens_column: USER-bge-m3
  label_column: label
  max_length: 1024

trainer:
  accelerator: "gpu"
  max_epochs: 4
  strategy:
    type: "fsdp1"
    find_unused_parameters: true
  val_check_interval: 0.2
  devices: 2
  precision: bf16-mixed
  log_every_n_steps: 25

early_stopping:
  monitor: "val_loss"
  patience: 5
  mode: "min"
  min_delta: 0.01

checkpoint:
  save_top_k: 3
  mode: "min"
  monitor: "val_loss"
  filename: "{epoch:02d}-{val_loss:.4f}"

model_id: e7801bc57fad4e64b06b6fa33d5cfc3b
tokenizer_id: 387811863bae48398d241934e61980c2
weights_prefix: "static_model"
