redis:
  host: 127.0.0.1
  port: 6379
  stream_name: validation_tasks

data:
  datasets:
    RuBQ-Reranking: a1c152d6491e43959cd8da88658e2e05
    Mixed-Summarization-Dataset: 2ef9572e96d94bc69ace31aa2de05387
    ru-HNP: 4cafe217d08242dc858ecf5e3347683e
  batch_size: 32
  num_workers: 5
  query_colname: query-tokens
  pos_colname: pos-tokens
  neg_colname: neg-tokens
  val_label_colname: label
  val_num_labels: 6

trainer:
  accelerator: "cuda"
  max_epochs: 12
  strategy:
    type: "ddp"
  val_check_interval: 0.2
  devices: 8
  precision: bf16-true
  log_every_n_steps: 25

early_stopping:
  monitor: "val_loss"
  patience: 3
  mode: "min"
  min_delta: 0.01

checkpoint:
  save_top_k: 3
  mode: "min"
  monitor: "val_loss"
  filename: "{epoch:02d}-{val_loss:.4f}"

teacher_model_id: af954495ff03440abc58790c4e41ff22
student_model_id: 749be3f1fd7341e09d33911c633c7c0a
tokenizer_id: 34beac693bfa4977b23cafea8b3d6379

model_cfg:
  model_type: static_embeddings
  embeddings_dropout: 0.2
