redis:
  host: 127.0.0.1
  port: 6379
  stream_name: validation_tasks

data:
  datasets:
    ru-HNP: 79fcccb7143c48f79ddf300bfd5ee1e4
    Mixed-Summarization: 173599873b46449fa9b4ad6350a657bf
  batch_size: 64
  num_workers: 4
  query_tok_colname: query-tokens
  pos_tok_colname: pos-tokens
  #neg_tok_colname: neg-tokens
  query_teacher_embedding_colname: query-embedding
  pos_teacher_embedding_colname: pos-embedding
  #neg_teacher_embedding_colname: neg-embedding
  val_label_colname: label
  val_num_labels: 6

trainer:
  accelerator: "cuda"
  max_epochs: 15
  strategy:
    type: "ddp"
  val_check_interval: 0.3
  devices: 4
  precision: bf16-true
  log_every_n_steps: 25

early_stopping:
  monitor: "val_loss"
  patience: 5
  mode: "min"
  min_delta: 0.01

checkpoint:
  save_top_k: 3
  mode: "min"
  monitor: "val_loss"
  filename: "|{epoch}|-|{step}|-|{val_loss:.5f}|"

teacher_model_id: af954495ff03440abc58790c4e41ff22
student_model_id: 2064bdd9dda642e0bcf05ef10cc7595a
tokenizer_id: 34beac693bfa4977b23cafea8b3d6379

model_cfg:
  model_type: lednik
  embeddings_dropout: 0.2
  attention_dropout: 0.0
  out_attn_dropout: 0.15
  mlp_dropout: 0.15
